#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# eval $(dircolors ~/.dircolors)

HISTFILE=~/.zsh_history
HISTSIZE=1000
SAVEHIST=1000

# case insensitive globbing
setopt NO_CASE_GLOB

[[ -a ~/project/kiss/shell-utils/zsh/.zsh_aliases ]]     && source ~/project/kiss/shell-utils/zsh/.zsh_aliases
[[ -a ~/project/kiss/shell-utils/zsh/.zsh_path ]]        && source ~/project/kiss/shell-utils/zsh/.zsh_path
[[ -a ~/project/kiss/shell-utils/zsh/.zsh_etc ]]         && source ~/project/kiss/shell-utils/zsh/.zsh_etc
[[ -a ~/.fzf.zsh ]]                                      && source ~/.fzf.zsh
[[ -a ~/project/kiss/shell-utils/zsh/.zsh_fzf ]]         && source ~/project/kiss/shell-utils/zsh/.zsh_fzf
[[ -a ~/project/kiss/shell-utils/zsh/.zsh_$(hostname) ]] && source ~/project/kiss/shell-utils/zsh/.zsh_$(hostname)

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Execute code only if STDERR is bound to a TTY.
if [[ -o INTERACTIVE && -t 2 ]]; then
  # Print a random, hopefully interesting, adage.
  if (( $+commands[fortune] )); then
    FORTUNEFILE="${HOME}/dotspacemacs/mycontribs/ttk-quotes/fortunes"
    if [[ -a ${FORTUNEFILE} ]]; then
      if [[ ! -a ${FORTUNEFILE}.dat ]]; then
        strfile ${FORTUNEFILE} >/dev/null
      fi
      #
      fortune ${FORTUNEFILE}
    fi
  fi
fi >&2
